ARG src_dir="/rtrmon"

FROM golang:alpine as builder
ARG src_dir

RUN apk --update --no-cache add git && \
    mkdir -p ${src_dir}

WORKDIR ${src_dir}
COPY . .

RUN go build cmd/rtrmon/rtrmon.go

FROM alpine:latest
ARG src_dir

RUN apk --update --no-cache add ca-certificates && \
    adduser -S -D -H -h / rtr
USER rtr

COPY --from=builder ${src_dir}/rtrmon /
ENTRYPOINT ["./rtrmon"]
