name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Test & Vet
      run: make test vet
      
    - name: Build
      run: |
        make dist-key
        GOOS=linux make build-gortr
        GOOS=darwin make build-gortr
        GOOS=windows EXTENSION=.exe make build-gortr
        GOOS=linux make build-rtrdump
        GOOS=darwin make build-rtrdump
        GOOS=windows EXTENSION=.exe make build-rtrdump
        GOOS=linux make build-rtrmon
        GOOS=darwin make build-rtrmon
        GOOS=windows EXTENSION=.exe make build-rtrmon
          
    - name: Install fpm
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm ruby ruby-dev
        sudo gem install fpm
        
    - name: Package
      run: make package-deb-gortr package-rpm-gortr

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*
        retention-days: 14
